/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qbasiclove;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;

/**
 *
 * @author Parham Alvani
 */
public class QBasicPanel extends javax.swing.JPanel {

    /**
     * Creates new form QBasicPanel
     */
    public QBasicPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2d = (Graphics2D) g;
        g2d.setPaint(Color.ORANGE);
        g2d.draw(new Line2D.Double(getWidth() / 2, 0, getWidth() / 2, getHeight()));
        g2d.draw(new Line2D.Double(0, getHeight() / 2, getWidth(), getHeight() / 2));
        for (int i = 0; i <= getHeight() / 2; i += 10) {
            g2d.draw(new Line2D.Double(getWidth() / 2, i, getWidth() / 2 + i, getHeight() / 2));
        }
        for (int i = 0; i <= getHeight() / 2; i += 10) {
            g2d.draw(new Line2D.Double(getWidth() / 2, i, getWidth() / 2 - i, getHeight() / 2));
        }
        for (int i = getHeight(); i >= getHeight() / 2; i -= 10) {
            g2d.draw(new Line2D.Double(getWidth() / 2, i, getWidth() / 2 + (getHeight() - i), getHeight() / 2));
        }
        for (int i = getHeight(); i >= getHeight() / 2; i -= 10) {
            g2d.draw(new Line2D.Double(getWidth() / 2, i, getWidth() / 2 - (getHeight() - i), getHeight() / 2));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
